from setuptools import setup
from torch.utils.cpp_extension import CppExtension, BuildExtension
import os

# Path to the ffmpeg build directory (generated by CMake)
ffmpeg_root = os.path.abspath("cpp/build/ffmpeg_install")

setup(
    name='clarification_cpp',
    ext_modules=[
        CppExtension(
            name='clarification.datas.clarification_cpp', 
            sources=[
                'cpp/src/bindings.cpp',
                'cpp/src/ClarificationDataset.cpp',
                'cpp/src/ClarificationLz4Dataset.cpp',
                'cpp/src/ClarificationOpusDataset.cpp',
            ],
            include_dirs=[
                'cpp/src',
                os.path.join(ffmpeg_root, 'include'),
                '/usr/local/include'
            ],
            library_dirs=[
                os.path.join(ffmpeg_root, 'lib'),
                '/usr/local/lib'
            ],
            runtime_library_dirs=[
                os.path.join(ffmpeg_root, 'lib'),
                '/usr/local/lib'
            ],
            libraries=['avformat', 'avcodec', 'avutil', 'swresample', 'lz4'],
            extra_compile_args=['-std=c++20', '-fopenmp'],
            extra_link_args=['-fopenmp']
        )
    ],
    cmdclass={
        'build_ext': BuildExtension
    }
)
